feat: add WI estimates
kysect/Tamgly pull request #33
Opened 2022-04-03 09:22 UTC by FrediKats

2022-04-04 06:20 UTC, Bibletoon commented on Source/Domain/Kysect.Tamgly.Core/Aggregates/WorkItemManager.cs
>          ArgumentNullException.ThrowIfNull(projects);
Для конфига проверку на null кажется тоже стоит добавить

2022-04-04 06:20 UTC, Bibletoon commented on Source/Domain/Kysect.Tamgly.Core/Aggregates/WorkItemManager.cs
> +    public IReadOnlyCollection<WorkItem> GetWorkItemWithWrongEstimates()
```suggestion
    public IReadOnlyCollection<WorkItem> GetWorkItemsWithWrongEstimates()
```
Не смотрел, есть ли где вызовы этого метода, будьте осторожны

2022-04-04 06:20 UTC, Bibletoon commented on Source/Domain/Kysect.Tamgly.Core/Entities/WorkItem.cs
> +    public TimeSpan? GetIntervalSum()
Чуть ниже метод, который может вернуть null, обладает приставкой `Try`, а этот нет, надо бы как-то унифицировать

2022-04-04 06:20 UTC, Bibletoon commented on Source/Domain/Kysect.Tamgly.Core/Entities/WorkItemTrackInterval.cs
> +    public void Validate()
А он точно должен быть публичным? Мне кажется проверка состояния объекта это только забота самого объекта

2022-04-04 06:20 UTC, Bibletoon commented on Source/Domain/Kysect.Tamgly.Core/Tools/WorkItemManagerConfig.cs
> +    private const double DefaultAcceptableEstimateDiff = 0.8;
Возможно стоит добавить что-то про то, что это дифф в долях/процентах, а то по этой строке не до конца очевидно

2022-04-04 06:25 UTC, ronimizy requested changes

2022-04-04 06:25 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Entities/WorkItemTrackInterval.cs
> +public readonly struct WorkItemTrackInterval : IEquatable<WorkItemTrackInterval>
EF не работает с value типами.

2022-04-04 06:25 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Entities/WorkItemTrackInterval.cs
> +    public DateTime? EndTime { get; }
Чтобы EF собирал объекты нужны `protected init`.

2022-04-04 06:25 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Entities/WorkItem.cs
> +        return result;
```suggestion
        var result = TimeSpan.Zero;

        foreach (WorkItemTrackInterval interval in Intervals)
        {
            TimeSpan? duration = interval.GetDuration();

            if (duration is null)
                continue;

            result = result.Add(duration.Value);
        }

        return result;
```

2022-04-04 06:25 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Aggregates/WorkItemManager.cs
> +    public IReadOnlyCollection<WorkItem> GetWorkItemWithWrongEstimates()
Мб `GetWorkItemWithUnacceptableEstimates`?

2022-04-04 06:28 UTC, Bibletoon commented on Source/Domain/Kysect.Tamgly.Core/Entities/WorkItemTrackInterval.cs
> +    public DateTime? EndTime { get; }
Пока что нет EF'a, так что добавление этого можно оставить на выполняющего ишую по его прикручивание

2022-04-05 14:17 UTC, FrediKats commented
Отвечу отдельным комментом, чтобы его не искать в резолвед штуках.

EF пока и не используется. Хочется таки не ставить во главе угла EF и написать решение, которое будет более правильным с точки зрения проектирования и потом уже натягивать его на EF. Не будет натягиваться? Напишем glue code, обёртки для репозиториев. Но домен хочется оставить чистым.

Разумеется, что штуки в духе "тут можно класс вместо структуры взять" совершенно не влияют и их можно пофиксить. Но всё же, хочется попробовать посмотреть какое будет решение без привязки к EF.

2022-04-05 14:18 UTC, FrediKats commented on Source/Domain/Kysect.Tamgly.Core/Entities/WorkItemTrackInterval.cs
> +public readonly struct WorkItemTrackInterval : IEquatable<WorkItemTrackInterval>
Записал в ишую.

2022-04-05 14:19 UTC, FrediKats commented on Source/Domain/Kysect.Tamgly.Core/Entities/WorkItem.cs
> +        return result;
Хм. Выглядит валидно. Действительно, интервал должен быть нулевым, а не null.

2022-04-05 14:22 UTC, FrediKats commented on Source/Domain/Kysect.Tamgly.Core/Aggregates/WorkItemManager.cs
> +    public IReadOnlyCollection<WorkItem> GetWorkItemWithWrongEstimates()
Сложный вопрос. Заведу отдельную ишую для этого, скорее всего. Не совсем согласен с Unacceptable т.к. нас интересуют как случаи когда времени ушло сильно больше, так и когда ушло сильно меньше. Назвать Unacceptable ситуацию когда закрыли таску на два дня раньше чем должно... Ну, можно. но странно.

2022-04-05 15:06 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Aggregates/WorkItemManager.cs
> +    public IReadOnlyCollection<WorkItem> GetWorkItemWithWrongEstimates()
Ну я прост про то, что в локальной функции процент сравнивается с полем `_config.AcceptableEstimateDiff` ну и тип Acceptable/Unacceptable. Мб я чёт не понимаю, тогда жду объяснительную бригаду по эстимейтам и мэтч процентам.

2022-04-07 15:02 UTC, FrediKats commented on Source/Domain/Kysect.Tamgly.Core/Aggregates/WorkItemManager.cs
> +    public IReadOnlyCollection<WorkItem> GetWorkItemWithWrongEstimates()
Завёл #36

2022-04-07 15:19 UTC, merged