feat: implement weekly backlog
kysect/Tamgly pull request #35
Opened 2022-04-03 18:08 UTC by FrediKats

close #14

2022-04-03 18:36 UTC, FrediKats commented
Теперь точно всё.

2022-04-04 06:40 UTC, Bibletoon commented on Source/Domain/Kysect.Tamgly.Core/Entities/DailyWorkItemBacklog.cs
> +    public WorkItemBacklog CurrentWeek { get; }
Я не очень понял зачем в беклоге за день иметь беклог за неделю

2022-04-04 06:40 UTC, Bibletoon commented on Source/Domain/Kysect.Tamgly.Core/Entities/WorkItem.cs
> +    public WorkItem(Guid id, string title, string? description, WorkItemState state, DateTime creationTime, ICollection<WorkItemTrackInterval> intervals, TimeSpan? estimate, WorkItemDeadline deadline
Где-то через 5 пр-ов эта строка перестанет помещаться на одисею и тогда её наконец засплитят на несколько...

2022-04-04 06:40 UTC, Bibletoon commented on Source/Domain/Kysect.Tamgly.Core/Entities/WorkItemBacklog.cs
> +        List<WorkItem> workItems = items
А почему отовсюду пропали на null?

2022-04-04 06:40 UTC, Bibletoon commented on Source/Domain/Kysect.Tamgly.Core/ValueObjects/TamglyTime.cs
> +    public static readonly DateTime ZeroDay = new DateTime(2021, 12, 27);
Вообще не выкупил зачем это и почему именно такое значение

2022-04-04 06:40 UTC, Bibletoon commented on Source/Domain/Kysect.Tamgly.Core/ValueObjects/TamglyTime.cs
> +        TimeSpan intervalFromZeroDay = second.Subtract(first);
Переменная называется `intervalFromZeroDay`, а `ZeroDay` никак не используется

2022-04-04 06:40 UTC, Bibletoon commented on Source/Domain/Kysect.Tamgly.Core/ValueObjects/WorkItemDeadline.cs
> +    public enum Type
Уф, название конечно опасное

2022-04-04 06:41 UTC, Bibletoon commented on Source/Domain/Kysect.Tamgly.Core/Entities/WorkItemBacklog.cs
> +        List<WorkItem> workItems = items
Комент оставил только тут, но проверки не было, по-моему, ни в одном статик методе

2022-04-04 06:42 UTC, ronimizy requested changes

2022-04-04 06:42 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Entities/DailyWorkItemBacklog.cs
> +    public WorkItemBacklog CurrentWeek { get; }
`protected init`

2022-04-04 06:42 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Entities/DailyWorkItemBacklog.cs
> +        CurrentWeek = currentWeek;
null-check

2022-04-04 06:42 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Entities/WeeklyWorkItemBacklog.cs
> +    public WorkItemBacklog CurrentWeek { get; }
`protected init`

2022-04-04 06:42 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Entities/WeeklyWorkItemBacklog.cs
> +        CurrentWeek = currentWeek;
null-check

2022-04-04 06:42 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Entities/WorkItem.cs
> +    public WorkItem(Guid id, string title, string? description, WorkItemState state, DateTime creationTime, ICollection<WorkItemTrackInterval> intervals, TimeSpan? estimate, WorkItemDeadline deadline
`WorkItemDeadline deadline` null-check

2022-04-04 06:42 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Entities/WorkItemBacklog.cs
> +    public ICollection<WorkItem> Items { get; }
`protected init`

2022-04-04 06:42 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Entities/WorkItemBacklog.cs
> +    public static WorkItemBacklog Create(WorkItemDeadline deadline, IReadOnlyCollection<WorkItem> items)
null-check

2022-04-04 06:42 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Entities/WorkItemBacklog.cs
> +    public WorkItemBacklog(WorkItemDeadline deadline, ICollection<WorkItem> items)
Constructor should not follow a method.

2022-04-04 06:42 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/ValueObjects/TamglyWeek.cs
> +public readonly struct TamglyWeek : IEquatable<TamglyWeek>
Юзаджей в сущностях не увидел, но если они будут, то надо будет переделать на класс.

2022-04-04 06:42 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/ValueObjects/WorkItemDeadline.cs
> +public readonly struct WorkItemDeadline : IEquatable<WorkItemDeadline>
То же про значимые типы

2022-04-04 06:42 UTC, ronimizy commented on Source/Presentation/Kysect.Tamgly.ConsoleClient/Program.cs
> +return;
```suggestion
```

2022-04-04 06:45 UTC, ronimizy commented
Кстати, ни в одной сущности нет пустого `protected` конструктора, это конечно можно добавить в рамках реализации #4, но будет большой дифф.

2022-04-04 06:54 UTC, Bibletoon commented
> Кстати, ни в одной сущности нет пустого `protected` конструктора, это конечно можно добавить в рамках реализации #4, но будет большой дифф.

Как вариант можно сделать отдельный пр с добавлением пустых конструкторов и init-ов и адаптацией под EF а потом уже добавлять EF, например, отпочковавшись от ветки с адаптацией

2022-04-04 07:10 UTC, ronimizy commented
> > Кстати, ни в одной сущности нет пустого `protected` конструктора, это конечно можно добавить в рамках реализации #4, но будет большой дифф.
> 
> Как вариант можно сделать отдельный пр с добавлением пустых конструкторов и init-ов и адаптацией под EF а потом уже добавлять EF, например, отпочковавшись от ветки с адаптацией

Валидно, ща в ишую добавлю.

2022-04-04 15:58 UTC, hrrrrustic commented on Source/Domain/Kysect.Tamgly.Core/Entities/WorkItem.cs
> +    public WorkItem(Guid id, string title, string? description, WorkItemState state, DateTime creationTime, ICollection<WorkItemTrackInterval> intervals, TimeSpan? estimate, WorkItemDeadline deadline
На фарш перепишут, чтобы ее вообще не было

2022-04-07 16:40 UTC, FrediKats commented on Source/Domain/Kysect.Tamgly.Core/Entities/DailyWorkItemBacklog.cs
> +    public WorkItemBacklog CurrentWeek { get; }
В #11 указывал. Идея в том, чтобы можно было посмотреть, что нужно прям сегодня и что можно взять с этой недели, если останется время.

2022-04-07 16:58 UTC, FrediKats commented on Source/Domain/Kysect.Tamgly.Core/Entities/WorkItem.cs
> +    public WorkItem(Guid id, string title, string? description, WorkItemState state, DateTime creationTime, ICollection<WorkItemTrackInterval> intervals, TimeSpan? estimate, WorkItemDeadline deadline
Добавил билдер.

2022-04-07 17:01 UTC, FrediKats commented on Source/Domain/Kysect.Tamgly.Core/ValueObjects/WorkItemDeadline.cs
> +    public enum Type
Заменил на WorkItemDeadlineType

2022-04-07 17:03 UTC, FrediKats commented on Source/Presentation/Kysect.Tamgly.ConsoleClient/Program.cs
> +return;
Оно там для того, чтобы брейкпоинт вешать)

2022-04-07 17:03 UTC, FrediKats commented on Source/Domain/Kysect.Tamgly.Core/ValueObjects/WorkItemDeadline.cs
> +public readonly struct WorkItemDeadline : IEquatable<WorkItemDeadline>
To next version )

2022-04-07 17:03 UTC, FrediKats commented on Source/Domain/Kysect.Tamgly.Core/ValueObjects/TamglyWeek.cs
> +public readonly struct TamglyWeek : IEquatable<TamglyWeek>
To next version )

2022-04-07 17:03 UTC, FrediKats commented on Source/Domain/Kysect.Tamgly.Core/Entities/WorkItemBacklog.cs
> +    public WorkItemBacklog(WorkItemDeadline deadline, ICollection<WorkItem> items)
fixed

2022-04-07 17:04 UTC, FrediKats commented on Source/Domain/Kysect.Tamgly.Core/Entities/WorkItemBacklog.cs
> +    public static WorkItemBacklog Create(WorkItemDeadline deadline, IReadOnlyCollection<WorkItem> items)
fixed

2022-04-07 17:04 UTC, FrediKats commented on Source/Domain/Kysect.Tamgly.Core/Entities/WorkItemBacklog.cs
> +    public ICollection<WorkItem> Items { get; }
To next version

2022-04-07 17:05 UTC, FrediKats commented on Source/Domain/Kysect.Tamgly.Core/Entities/WorkItem.cs
> +    public WorkItem(Guid id, string title, string? description, WorkItemState state, DateTime creationTime, ICollection<WorkItemTrackInterval> intervals, TimeSpan? estimate, WorkItemDeadline deadline
Это структура.

2022-04-07 17:05 UTC, FrediKats commented on Source/Domain/Kysect.Tamgly.Core/Entities/WeeklyWorkItemBacklog.cs
> +        CurrentWeek = currentWeek;
fixed

2022-04-07 17:06 UTC, FrediKats commented on Source/Domain/Kysect.Tamgly.Core/Entities/WeeklyWorkItemBacklog.cs
> +    public WorkItemBacklog CurrentWeek { get; }
To next version

2022-04-07 17:07 UTC, FrediKats commented on Source/Domain/Kysect.Tamgly.Core/Entities/DailyWorkItemBacklog.cs
> +        CurrentWeek = currentWeek;
fixed

2022-04-07 17:07 UTC, FrediKats commented on Source/Domain/Kysect.Tamgly.Core/Entities/DailyWorkItemBacklog.cs
> +    public WorkItemBacklog CurrentWeek { get; }
To next version

2022-04-07 17:08 UTC, FrediKats commented on Source/Domain/Kysect.Tamgly.Core/Entities/WorkItemBacklog.cs
> +        List<WorkItem> workItems = items
PR'ы видимо параллельно пилил, видимо были в одном, но не попали во второй.

2022-04-07 17:27 UTC, FrediKats commented on Source/Domain/Kysect.Tamgly.Core/ValueObjects/TamglyTime.cs
> +    public static readonly DateTime ZeroDay = new DateTime(2021, 12, 27);
Описал тут - https://github.com/kysect/Tamgly/blob/master/README.md#%D1%87%D1%82%D0%BE-%D0%B5%D1%81%D1%82%D1%8C-%D0%B2%D1%80%D0%B5%D0%BC%D1%8F

2022-04-07 17:31 UTC, merged