feat: implement WI block detecting
kysect/Tamgly pull request #46
Opened 2022-04-10 14:55 UTC by FrediKats

close #20

2022-04-10 19:35 UTC, ronimizy requested changes
- Странные местные оптимизации. Не вижу смысла писать LINQ и LINQ-free код в скопе одного метода. Вряд ли сейчас это будет проблемой производительности, а когда будет это стоит выносить в отдельные методы чтобы нормально читалось.
- Графы давно не повторял, а и думать немного лень сейчас. Как работает эта проверка на блоки? Почему переменная `_blockingGraph` в `BlockerLinkManager` не используется?

2022-04-10 19:35 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Graphs/GraphLink.cs
> +    public GraphLink Reverse() => new GraphLink(From: To, To: From);
```suggestion
    public GraphLink Reversed() => new GraphLink(From: To, To: From);
```

2022-04-10 19:35 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Graphs/GraphNode.cs
> +    public Guid Id { get; set; }
why `set`?

2022-04-10 19:35 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Graphs/GraphNode.cs
> +    public IReadOnlyCollection<GraphNode<T>> DirectChild { get; set; }
more like `Children`

2022-04-10 19:35 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Graphs/GraphNode.cs
> +    }
Очень странный метод.
- Непонятный нейминг.
- Отсутствие доки.
- В одном месте мы возвращаем значение текущего узла, в другом нет.

Выглядит будто было проиграно в рекурсию, мне кажется что подразумевалось что-то такое: 
```suggestion
    public IReadOnlyCollection<GraphPath<T>> EnumeratePathToLeaves()
    {
        if (!DirectChild.Any())
        {
            return new[] { GraphPath<T>.Empty.AppendToStart(Value) };
        }
        
        return DirectChild
            .SelectMany(c => c.EnumeratePathToLeaves())
            .Select(p => p.AppendToStart(Value))
            .ToList();
    }
```

(Если нет, то скорее всего где-то есть костыли)

2022-04-10 19:35 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Graphs/GraphNode.cs
> +    }
```suggestion
    public GraphNode<T>? Find(Guid id)
    {
        if (Id == id)
            return this;

         return DirectChild
            .Select(node => node.Find(id))
            .FirstOrDefault(founded => founded is not null);
    }
```

2022-04-10 19:35 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Graphs/GraphBuilder.cs
> +        GraphValueResolver<T> resolver)
```suggestion
        IGraphValueResolver<T> resolver)
```

2022-04-10 19:35 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Graphs/GraphBuildResult.cs
> +    }
```suggestion
    public GraphNode<T> GetValue(Guid id)
    {
        GraphNode<T>? found = Roots
            .Select(root => root.Find(id))
            .FirstOrDefault(value => value is not null);

        return found ?? throw new TamglyException($"Work item with id {id} was not found");
    }
```

2022-04-10 19:35 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Graphs/GraphBuilder.cs
> +            result.Add(BuildNode(rootNode, nodeLinks, resolver));
```suggestion
        List<GraphNode<T>> result = rootNodes
            .Select(rootNode => BuildNode(rootNode, nodeLinks, resolver))
            .ToList();
```

2022-04-10 19:35 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Graphs/GraphBuilder.cs
> +    }
```suggestion
    private static GraphNode<T> BuildNode<T>(Guid id, ILookup<Guid, Guid> nodeLinks, IGraphValueResolver<T> resolver)
    {
        IReadOnlyCollection<GraphNode<T>> children = nodeLinks.Contains(id)
            ? BuildChildren(nodeLinks[id], nodeLinks, resolver)
            : Array.Empty<GraphNode<T>>();

        return new GraphNode<T>(id, resolver.Resolve(id), children);
    }

    private static IReadOnlyCollection<GraphNode<T>> BuildChildren<T>(
        IEnumerable<Guid> identifiers,
        ILookup<Guid, Guid> nodeLinks,
        IGraphValueResolver<T> resolver)
    {
        return identifiers
            .Select(childId => BuildNode(childId, nodeLinks, resolver))
            .ToList();
    }
```

2022-04-10 19:35 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Graphs/GraphValueResolver.cs
> +}
Не используется

2022-04-10 19:35 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Aggregates/BlockerLinkManager.cs
> +    private GraphBuildResult<IWorkItem> _blockingGraph;
только обновляется, не используется

2022-04-10 20:08 UTC, ronimizy commented on Source/Domain/Kysect.Tamgly.Core/Graphs/GraphNode.cs
> +    }
Ну и оно не используется -_-

2022-04-11 06:34 UTC, ronimizy commented
Вообще всё это выглядит как какой-то оверинжиниринг. 
Кажется что для того чтобы определить заблокирована ли таска не нужно придумывать свою библиотеку с графами.

2022-04-24 12:35 UTC, FrediKats commented
> Странные местные оптимизации

Это не были оптимизации. Я, видимо, просто не осилил линки.

> _blockingGraph 

Я в ридми описал. Проблема в том, что с одной стороны нам нужно делать обходы по добавленным рёбрам, чтобы построить подграф из задач, которые блокируются рутовой нодой, чтобы получить информацию о том, что за приоритеты должен быть у рута (напомню, что если задача является блокируется более приоритетную, то она и должна быть такого же приоритета). С другой стороны, для того, чтобы найти все задачи, которые блокируют рут - нужно построить подграф по ревёрснутым рёбрам. Поэтому там и появилось два разных графа.

2022-04-24 12:44 UTC, FrediKats commented on Source/Domain/Kysect.Tamgly.Core/Graphs/GraphNode.cs
> +    }
Да, действительно была ошибки и там нужно Value подставлять. Метод действительно не очевидный без юзаджей. Это я проиграл в итерации и начал делать реализацию на будущее, чтобы более оптимально выбираться задачу. Думаю, лучше пока удалить т.к. не будет использоваться.

2022-04-24 13:12 UTC, FrediKats commented on Source/Domain/Kysect.Tamgly.Core/Aggregates/BlockerLinkManager.cs
> +    private GraphBuildResult<IWorkItem> _blockingGraph;
В следующем PR с приоритетами заюзаю. Добавил сразу два т.к. тут не самая очевидная логика была.

2022-04-24 13:47 UTC, merged